### ISSUE TITLE
Decompose code

### ISSUE THREAD

**Issue by leofanxiong** [ethanlee515/jasmin-dilithium#1]
https://github.com/ethanlee515/jasmin-dilithium/blob/3e9180ee1c73504f5efd8a737af291284459ce46/src/high-low-order.jazz#L24

This function seems different from the ref-implementation: https://github.com/ethanlee515/dilithium/blob/dddcc7569846199dc657377137ba21411526ed7a/ref/rounding.c#L39. The ref-implementation outputs just a1 and the #if part is not captured.

**Comment by ethanlee515** [comment]
The reference implementation outputs both a0 and a1. Due to limitations to the C syntax, a0 is implemented as a so-called _out-parameter_.

The function signature is `int32_t decompose(int32_t *a0, int32_t a)`. Notice that it takes a _pointer to_ `a0`. It then never uses the (pointed-to) value of `a0`, but overwrites it directly on line 51 as `*a0  = a - a1*2*GAMMA2;`. This indicates that `a0` isn't treated as an input, but as an extra output.

In Jasmin we don't need this type of constructions, as we can just output multiple values.

The `#if` isn't captured because `GAMMA2` varies only with security level. Right now I want to get security level 3 right before worrying about other ones.

**Comment by leofanxiong** [comment]
I see. So the code you wrote is tailored to level 3 parameters?

**Comment by ethanlee515** [comment]
For now, yeah. We'll probably have to do something about it sooner or later though.

**Comment by leofanxiong** [comment]
I think sooner may be better. We don't want to hardcode the code at level 3 parameters.
